Refer to version 3.x on download page
mapproxy/mapproxy-homepage pull request #6
Opened 2024-08-27 14:26 UTC by marcjansen

Title says it all.

2024-08-27 14:33 UTC, hblitza approved these changes

2024-08-27 14:33 UTC, hblitza commented
Thanks

2024-08-27 14:52 UTC, weskamm commented
In my opinion we can remove the relation to a specific version. Maybe we need to release version 4.0.0 tomorrow? I think there is no need to have that information (current major) in the static docs

2024-08-28 07:46 UTC, marcjansen commented
> In my opinion we can remove the relation to a specific version. Maybe we need to release version 4.0.0 tomorrow? I think there is no need to have that information (current major) in the static docs

What is your suggestion? Should I close this and you'll make another PR with what you think is more longliving?

2024-08-28 08:01 UTC, weskamm requested changes

2024-08-28 08:01 UTC, weskamm commented on src/pages/download.md
>  This is the current release. It is released under the [Apache Software License 2.0](http://www.apache.org/licenses/LICENSE-2.0.html).
```suggestion
MapProxy is released under the [Apache Software License 2.0](http://www.apache.org/licenses/LICENSE-2.0.html).
```

2024-08-28 15:22 UTC, marcjansen commented
Thanks for the suggestions, I accepted all of them.

Would you mind having another look?

2024-08-29 06:26 UTC, weskamm commented
Nice, thanks!

2024-08-29 06:26 UTC, merged